name: finlytics
description: Finlytics - app de gestão financeira pessoal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1     # state management (MVVM via notifiers)
  go_router: ^13.2.0           # navegação declarativa
  dio: ^5.4.1                  # HTTP client
  flutter_secure_storage: ^10.3.1  # tokens (Keychain/Keystore)
  dartz: ^0.10.1               # Either<Failure, T>
  equatable: ^2.0.5
  intl: ^0.19.0                # moeda/data pt-BR
  fl_chart: ^0.66.2            # gráficos
  local_auth: ^2.2.0           # biometria
  get_it: ^7.6.7               # DI

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
